import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

// Review 120, 124, 128: Corregir rutas por el modelo checar ObjectMenu
const routes: Routes = [

    {
        path: 'DynamicSearch',
        loadChildren: () =>
            import('./dynamicsearch/dynamicsearch.module').then(m => m.DynamicSearchModule)
    },
    {
        path: 'workflow',
        loadChildren: () =>
            import('./components/workflow/workflow.module').then(m => m.WorkflowModule)
    },
    {
        path: 'dashboard',
        loadChildren: () =>
            import('./dashboard/dashboard.module').then(m => m.DashboardModule)
    },
    {
        path: 'email',
        loadChildren: () => import('./email/email.module').then(m => m.EmailModule)
    },
    {
        path: 'apps',
        loadChildren: () => import('./apps/apps.module').then(m => m.AppsModule)
    },
    {
        path: 'widget',
        loadChildren: () =>
            import('./widget/widget.module').then(m => m.WidgetModule)
    },
    {
        path: 'ui',
        loadChildren: () => import('./ui/ui.module').then(m => m.UiModule)
    },
    {
        path: 'forms',
        loadChildren: () => import('./forms/forms.module').then(m => m.FormModule)
    },
    {
        path: 'tables',
        loadChildren: () =>
            import('./tables/tables.module').then(m => m.TablesModule)
    },
    {
        path: 'media',
        loadChildren: () => import('./media/media.module').then(m => m.MediaModule)
    },
    {
        path: 'charts',
        loadChildren: () =>
            import('./charts/charts.module').then(m => m.ChartsModule)
    },
    {
        path: 'timeline',
        loadChildren: () =>
            import('./timeline/timeline.module').then(m => m.TimelineModule)
    },
    {
        path: 'icons',
        loadChildren: () => import('./icons/icons.module').then(m => m.IconsModule)
    },
    {
        path: 'authentication',
        loadChildren: () =>
            import('./authentication/authentication.module').then(
                m => m.AuthenticationModule
            )
    },
    {
        path: 'extra-pages',
        loadChildren: () =>
            import('./extra-pages/extra-pages.module').then(m => m.ExtraPagesModule)
    },
    {
        path: 'maps',
        loadChildren: () => import('./maps/maps.module').then(m => m.MapsModule)
    },
    {
        path: 'Security',
        loadChildren: () => import('./views/security/security.module').then(m => m.SecurityModule)
    },
    {
        path: '',
        redirectTo: 'authentication',
        pathMatch: 'full'
    },
    { path: 'Catalogo_codigo_ATA', loadChildren: () => import('./views/Catalogo_codigo_ATA/Catalogo_codigo_ATA.module').then(m => m.Catalogo_codigo_ATAModule) },
    { path: 'Ciudad', loadChildren: () => import('./views/Ciudad/Ciudad.module').then(m => m.CiudadModule) },
    { path: 'Estado', loadChildren: () => import('./views/Estado/Estado.module').then(m => m.EstadoModule) },
    { path: 'Modelos', loadChildren: () => import('./views/Modelos/Modelos.module').then(m => m.ModelosModule) },
    { path: 'Pais', loadChildren: () => import('./views/Pais/Pais.module').then(m => m.PaisModule) },
    { path: 'Tipo_de_Cambio', loadChildren: () => import('./views/Tipo_de_Cambio/Tipo_de_Cambio.module').then(m => m.Tipo_de_CambioModule) },
    { path: 'Actividades_de_los_Colaboradores', loadChildren: () => import('./views/Actividades_de_los_Colaboradores/Actividades_de_los_Colaboradores.module').then(m => m.Actividades_de_los_ColaboradoresModule) },
    { path: 'Agrupacion_Concepto_Balance_General', loadChildren: () => import('./views/Agrupacion_Concepto_Balance_General/Agrupacion_Concepto_Balance_General.module').then(m => m.Agrupacion_Concepto_Balance_GeneralModule) },
    { path: 'Agrupacion_de_Reportes', loadChildren: () => import('./views/Agrupacion_de_Reportes/Agrupacion_de_Reportes.module').then(m => m.Agrupacion_de_ReportesModule) },
    { path: 'Ano', loadChildren: () => import('./views/Ano/Ano.module').then(m => m.AnoModule) },
    { path: 'Aplicacion__de_Prestamo', loadChildren: () => import('./views/Aplicacion__de_Prestamo/Aplicacion__de_Prestamo.module').then(m => m.Aplicacion__de_PrestamoModule) },
    { path: 'Salida_en_Almacen_de_partes', loadChildren: () => import('./views/Salida_en_Almacen_de_partes/Salida_en_Almacen_de_partes.module').then(m => m.Salida_en_Almacen_de_partesModule) },
    { path: 'Autorizacion', loadChildren: () => import('./views/Autorizacion/Autorizacion.module').then(m => m.AutorizacionModule) },
    { path: 'Autorizacion_de_Prefactura_Aerovics', loadChildren: () => import('./views/Autorizacion_de_Prefactura_Aerovics/Autorizacion_de_Prefactura_Aerovics.module').then(m => m.Autorizacion_de_Prefactura_AerovicsModule) },
    { path: 'Ayuda_de_respuesta_crear_reporte', loadChildren: () => import('./views/Ayuda_de_respuesta_crear_reporte/Ayuda_de_respuesta_crear_reporte.module').then(m => m.Ayuda_de_respuesta_crear_reporteModule) },
    { path: 'Bitacora', loadChildren: () => import('./views/Bitacora/Bitacora.module').then(m => m.BitacoraModule) },
    { path: 'Boletines_Directivas_aeronavegatibilidad', loadChildren: () => import('./views/Boletines_Directivas_aeronavegatibilidad/Boletines_Directivas_aeronavegatibilidad.module').then(m => m.Boletines_Directivas_aeronavegatibilidadModule) },
    { path: 'Calendario_Configuracion', loadChildren: () => import('./views/Calendario_Configuracion/Calendario_Configuracion.module').then(m => m.Calendario_ConfiguracionModule) },
    { path: 'Calendario_Configuracion_Rol', loadChildren: () => import('./views/Calendario_Configuracion_Rol/Calendario_Configuracion_Rol.module').then(m => m.Calendario_Configuracion_RolModule) },
    { path: 'Carga_Manual', loadChildren: () => import('./views/Carga_Manual/Carga_Manual.module').then(m => m.Carga_ManualModule) },
    { path: 'Cargo_de_Tripulante', loadChildren: () => import('./views/Cargo_de_Tripulante/Cargo_de_Tripulante.module').then(m => m.Cargo_de_TripulanteModule) },
    { path: 'Cargos', loadChildren: () => import('./views/Cargos/Cargos.module').then(m => m.CargosModule) },
    { path: 'Cat__reportes_prestablecidos', loadChildren: () => import('./views/Cat__reportes_prestablecidos/Cat__reportes_prestablecidos.module').then(m => m.Cat__reportes_prestablecidosModule) },
    { path: 'Catalago_Manual_de_Usuario', loadChildren: () => import('./views/Catalago_Manual_de_Usuario/Catalago_Manual_de_Usuario.module').then(m => m.Catalago_Manual_de_UsuarioModule) },
    { path: 'Catalogo_Actividades_de_Colaboradores', loadChildren: () => import('./views/Catalogo_Actividades_de_Colaboradores/Catalogo_Actividades_de_Colaboradores.module').then(m => m.Catalogo_Actividades_de_ColaboradoresModule) },
    { path: 'Aeropuertos', loadChildren: () => import('./views/Aeropuertos/Aeropuertos.module').then(m => m.AeropuertosModule) },
    { path: 'Aeronave', loadChildren: () => import('./views/Aeronave/Aeronave.module').then(m => m.AeronaveModule) },
    { path: 'Creacion_de_Proveedores', loadChildren: () => import('./views/Creacion_de_Proveedores/Creacion_de_Proveedores.module').then(m => m.Creacion_de_ProveedoresModule) },
    { path: 'Herramientas', loadChildren: () => import('./views/Herramientas/Herramientas.module').then(m => m.HerramientasModule) },
    { path: 'Listado_de_Materiales', loadChildren: () => import('./views/Listado_de_Materiales/Listado_de_Materiales.module').then(m => m.Listado_de_MaterialesModule) },
    { path: 'Partes', loadChildren: () => import('./views/Partes/Partes.module').then(m => m.PartesModule) },
    { path: 'Catalogo_Reportes', loadChildren: () => import('./views/Catalogo_Reportes/Catalogo_Reportes.module').then(m => m.Catalogo_ReportesModule) },
    { path: 'Catalogo_servicios', loadChildren: () => import('./views/Catalogo_servicios/Catalogo_servicios.module').then(m => m.Catalogo_serviciosModule) },
    { path: 'Catalogo_Tipo_de_Vencimiento', loadChildren: () => import('./views/Catalogo_Tipo_de_Vencimiento/Catalogo_Tipo_de_Vencimiento.module').then(m => m.Catalogo_Tipo_de_VencimientoModule) },
    { path: 'Categoria_de_Partes', loadChildren: () => import('./views/Categoria_de_Partes/Categoria_de_Partes.module').then(m => m.Categoria_de_PartesModule) },
    { path: 'Categorias_y_Documentos_Requeridos', loadChildren: () => import('./views/Categorias_y_Documentos_Requeridos/Categorias_y_Documentos_Requeridos.module').then(m => m.Categorias_y_Documentos_RequeridosModule) },
    { path: 'Categorias_y_Documentos_Requeridos_de_Partes', loadChildren: () => import('./views/Categorias_y_Documentos_Requeridos_de_Partes/Categorias_y_Documentos_Requeridos_de_Partes.module').then(m => m.Categorias_y_Documentos_Requeridos_de_PartesModule) },
    { path: 'Causa_de_remocion', loadChildren: () => import('./views/Causa_de_remocion/Causa_de_remocion.module').then(m => m.Causa_de_remocionModule) },
    { path: 'Cierre_de_Vuelo', loadChildren: () => import('./views/Cierre_de_Vuelo/Cierre_de_Vuelo.module').then(m => m.Cierre_de_VueloModule) },
    { path: 'Clasificacion_de_aeronavegabilidad', loadChildren: () => import('./views/Clasificacion_de_aeronavegabilidad/Clasificacion_de_aeronavegabilidad.module').then(m => m.Clasificacion_de_aeronavegabilidadModule) },
    { path: 'Clasificacion_de_proveedores', loadChildren: () => import('./views/Clasificacion_de_proveedores/Clasificacion_de_proveedores.module').then(m => m.Clasificacion_de_proveedoresModule) },
    { path: 'Cliente', loadChildren: () => import('./views/Cliente/Cliente.module').then(m => m.ClienteModule) },
    { path: 'Cliente_Facturacion', loadChildren: () => import('./views/Cliente_Facturacion/Cliente_Facturacion.module').then(m => m.Cliente_FacturacionModule) },
    { path: 'CMP_a_Cotizar', loadChildren: () => import('./views/CMP_a_Cotizar/CMP_a_Cotizar.module').then(m => m.CMP_a_CotizarModule) },
    { path: 'Codigo_Computarizado', loadChildren: () => import('./views/Codigo_Computarizado/Codigo_Computarizado.module').then(m => m.Codigo_ComputarizadoModule) },
    { path: 'Colores', loadChildren: () => import('./views/Colores/Colores.module').then(m => m.ColoresModule) },
    { path: 'Comisariato_y_notas_de_vuelo', loadChildren: () => import('./views/Comisariato_y_notas_de_vuelo/Comisariato_y_notas_de_vuelo.module').then(m => m.Comisariato_y_notas_de_vueloModule) },
    { path: 'Comparativo_de_Proveedores_Piezas', loadChildren: () => import('./views/Comparativo_de_Proveedores_Piezas/Comparativo_de_Proveedores_Piezas.module').then(m => m.Comparativo_de_Proveedores_PiezasModule) },
    { path: 'Comparativo_de_Proveedores_Materiales', loadChildren: () => import('./views/Comparativo_de_Proveedores_Materiales/Comparativo_de_Proveedores_Materiales.module').then(m => m.Comparativo_de_Proveedores_MaterialesModule) },
    { path: 'Comparativo_de_Proveedores_Servicios', loadChildren: () => import('./views/Comparativo_de_Proveedores_Servicios/Comparativo_de_Proveedores_Servicios.module').then(m => m.Comparativo_de_Proveedores_ServiciosModule) },
    { path: 'Concepto', loadChildren: () => import('./views/Concepto/Concepto.module').then(m => m.ConceptoModule) },
    { path: 'Concepto_Balance_General', loadChildren: () => import('./views/Concepto_Balance_General/Concepto_Balance_General.module').then(m => m.Concepto_Balance_GeneralModule) },
    { path: 'Concepto_de_Comisariato_Normal', loadChildren: () => import('./views/Concepto_de_Comisariato_Normal/Concepto_de_Comisariato_Normal.module').then(m => m.Concepto_de_Comisariato_NormalModule) },
    { path: 'Concepto_de_Gasto_de_Aeronave', loadChildren: () => import('./views/Concepto_de_Gasto_de_Aeronave/Concepto_de_Gasto_de_Aeronave.module').then(m => m.Concepto_de_Gasto_de_AeronaveModule) },
    { path: 'Concepto_de_Gasto_de_Empleado', loadChildren: () => import('./views/Concepto_de_Gasto_de_Empleado/Concepto_de_Gasto_de_Empleado.module').then(m => m.Concepto_de_Gasto_de_EmpleadoModule) },
    { path: 'Concepto_Estado_de_Resultado', loadChildren: () => import('./views/Concepto_Estado_de_Resultado/Concepto_Estado_de_Resultado.module').then(m => m.Concepto_Estado_de_ResultadoModule) },
    { path: 'Condicion_del_item', loadChildren: () => import('./views/Condicion_del_item/Condicion_del_item.module').then(m => m.Condicion_del_itemModule) },
    { path: 'Configuracion_de_Codigo_Computarizado', loadChildren: () => import('./views/Configuracion_de_Codigo_Computarizado/Configuracion_de_Codigo_Computarizado.module').then(m => m.Configuracion_de_Codigo_ComputarizadoModule) },
    { path: 'Impuestos', loadChildren: () => import('./views/Impuestos/Impuestos.module').then(m => m.ImpuestosModule) },
    { path: 'Configuracion_de_Notificacion', loadChildren: () => import('./views/Configuracion_de_Notificacion/Configuracion_de_Notificacion.module').then(m => m.Configuracion_de_NotificacionModule) },
    { path: 'Pasajeros', loadChildren: () => import('./views/Pasajeros/Pasajeros.module').then(m => m.PasajerosModule) },
    { path: 'Configuracion_de_Politicas_de_Viaticos', loadChildren: () => import('./views/Configuracion_de_Politicas_de_Viaticos/Configuracion_de_Politicas_de_Viaticos.module').then(m => m.Configuracion_de_Politicas_de_ViaticosModule) },
    { path: 'Configuracion_de_tecnicos_e_inspectores', loadChildren: () => import('./views/Configuracion_de_tecnicos_e_inspectores/Configuracion_de_tecnicos_e_inspectores.module').then(m => m.Configuracion_de_tecnicos_e_inspectoresModule) },
    { path: 'Creacion_de_Usuarios', loadChildren: () => import('./views/Creacion_de_Usuarios/Creacion_de_Usuarios.module').then(m => m.Creacion_de_UsuariosModule) },
    { path: 'Consecutivo_Numero_de_vuelo', loadChildren: () => import('./views/Consecutivo_Numero_de_vuelo/Consecutivo_Numero_de_vuelo.module').then(m => m.Consecutivo_Numero_de_vueloModule) },
    { path: 'Control_de_Calibracion_de_Equipo_y_Herramienta', loadChildren: () => import('./views/Control_de_Calibracion_de_Equipo_y_Herramienta/Control_de_Calibracion_de_Equipo_y_Herramienta.module').then(m => m.Control_de_Calibracion_de_Equipo_y_HerramientaModule) },
    { path: 'Control_de_Componentes', loadChildren: () => import('./views/Control_de_Componentes/Control_de_Componentes.module').then(m => m.Control_de_ComponentesModule) },
    { path: 'Control_Componentes_de_la_Aeronave', loadChildren: () => import('./views/Control_Componentes_de_la_Aeronave/Control_Componentes_de_la_Aeronave.module').then(m => m.Control_Componentes_de_la_AeronaveModule) },
    { path: 'Control_de_Herramientas__Materiales_y_Equipo_prestado', loadChildren: () => import('./views/Control_de_Herramientas__Materiales_y_Equipo_prestado/Control_de_Herramientas__Materiales_y_Equipo_prestado.module').then(m => m.Control_de_Herramientas__Materiales_y_Equipo_prestadoModule) },
    { path: 'Coordinacion_Avisos', loadChildren: () => import('./views/Coordinacion_Avisos/Coordinacion_Avisos.module').then(m => m.Coordinacion_AvisosModule) },
    { path: 'Coord__de_Vuelo__Documentacion', loadChildren: () => import('./views/Coord__de_Vuelo__Documentacion/Coord__de_Vuelo__Documentacion.module').then(m => m.Coord__de_Vuelo__DocumentacionModule) },
    { path: 'Coordinacion_Handling', loadChildren: () => import('./views/Coordinacion_Handling/Coordinacion_Handling.module').then(m => m.Coordinacion_HandlingModule) },
    { path: 'Coordinacion_Pasajeros', loadChildren: () => import('./views/Coordinacion_Pasajeros/Coordinacion_Pasajeros.module').then(m => m.Coordinacion_PasajerosModule) },
    { path: 'Coord__de_Vuelo__Tripulacion', loadChildren: () => import('./views/Coord__de_Vuelo__Tripulacion/Coord__de_Vuelo__Tripulacion.module').then(m => m.Coord__de_Vuelo__TripulacionModule) },
    { path: 'Costos_de_Importacion', loadChildren: () => import('./views/Costos_de_Importacion/Costos_de_Importacion.module').then(m => m.Costos_de_ImportacionModule) },
    { path: 'Cotizacion', loadChildren: () => import('./views/Cotizacion/Cotizacion.module').then(m => m.CotizacionModule) },
    { path: 'Creacion_de_Clientes', loadChildren: () => import('./views/Creacion_de_Clientes/Creacion_de_Clientes.module').then(m => m.Creacion_de_ClientesModule) },
    { path: 'Crear_Reporte', loadChildren: () => import('./views/Crear_Reporte/Crear_Reporte.module').then(m => m.Crear_ReporteModule) },
    { path: 'Departamento', loadChildren: () => import('./views/Departamento/Departamento.module').then(m => m.DepartamentoModule) },
    { path: 'Discrepancias_Pendientes_Salida', loadChildren: () => import('./views/Discrepancias_Pendientes_Salida/Discrepancias_Pendientes_Salida.module').then(m => m.Discrepancias_Pendientes_SalidaModule) },
    { path: 'Documentacion_de_Aeronave', loadChildren: () => import('./views/Documentacion_de_Aeronave/Documentacion_de_Aeronave.module').then(m => m.Documentacion_de_AeronaveModule) },
    { path: 'Documentacion_de_Pasajero', loadChildren: () => import('./views/Documentacion_de_Pasajero/Documentacion_de_Pasajero.module').then(m => m.Documentacion_de_PasajeroModule) },
    { path: 'Documentos_Requeridos', loadChildren: () => import('./views/Documentos_Requeridos/Documentos_Requeridos.module').then(m => m.Documentos_RequeridosModule) },
    { path: 'Ejecucion_de_Vuelo', loadChildren: () => import('./views/Ejecucion_de_Vuelo/Ejecucion_de_Vuelo.module').then(m => m.Ejecucion_de_VueloModule) },
    { path: 'Equipo_de_Navegacion', loadChildren: () => import('./views/Equipo_de_Navegacion/Equipo_de_Navegacion.module').then(m => m.Equipo_de_NavegacionModule) },
    { path: 'Estatus_Aeronave', loadChildren: () => import('./views/Estatus_Aeronave/Estatus_Aeronave.module').then(m => m.Estatus_AeronaveModule) },
    { path: 'Estatus_autorizacion_de_prefactura', loadChildren: () => import('./views/Estatus_autorizacion_de_prefactura/Estatus_autorizacion_de_prefactura.module').then(m => m.Estatus_autorizacion_de_prefacturaModule) },
    { path: 'Estatus_de_Calibracion', loadChildren: () => import('./views/Estatus_de_Calibracion/Estatus_de_Calibracion.module').then(m => m.Estatus_de_CalibracionModule) },
    { path: 'Estatus_de_Cierre_de_Vuelo', loadChildren: () => import('./views/Estatus_de_Cierre_de_Vuelo/Estatus_de_Cierre_de_Vuelo.module').then(m => m.Estatus_de_Cierre_de_VueloModule) },
    { path: 'Estatus_de_Cliente', loadChildren: () => import('./views/Estatus_de_Cliente/Estatus_de_Cliente.module').then(m => m.Estatus_de_ClienteModule) },
    { path: 'Estatus_de_CMP_a_Cotizar', loadChildren: () => import('./views/Estatus_de_CMP_a_Cotizar/Estatus_de_CMP_a_Cotizar.module').then(m => m.Estatus_de_CMP_a_CotizarModule) },
    { path: 'Estatus_de_componente', loadChildren: () => import('./views/Estatus_de_componente/Estatus_de_componente.module').then(m => m.Estatus_de_componenteModule) },
    { path: 'Estatus_de_Confirmacion', loadChildren: () => import('./views/Estatus_de_Confirmacion/Estatus_de_Confirmacion.module').then(m => m.Estatus_de_ConfirmacionModule) },
    { path: 'Estatus_de_Cotizacion', loadChildren: () => import('./views/Estatus_de_Cotizacion/Estatus_de_Cotizacion.module').then(m => m.Estatus_de_CotizacionModule) },
    { path: 'Estatus_de_facturacion_de_vuelo', loadChildren: () => import('./views/Estatus_de_facturacion_de_vuelo/Estatus_de_facturacion_de_vuelo.module').then(m => m.Estatus_de_facturacion_de_vueloModule) },
    { path: 'Estatus_de_Funcionalidad_para_Notificacion', loadChildren: () => import('./views/Estatus_de_Funcionalidad_para_Notificacion/Estatus_de_Funcionalidad_para_Notificacion.module').then(m => m.Estatus_de_Funcionalidad_para_NotificacionModule) },
    { path: 'Estatus_de_Gastos_de_Vuelo', loadChildren: () => import('./views/Estatus_de_Gastos_de_Vuelo/Estatus_de_Gastos_de_Vuelo.module').then(m => m.Estatus_de_Gastos_de_VueloModule) },
    { path: 'Estatus_de_Orden_de_Trabajo', loadChildren: () => import('./views/Estatus_de_Orden_de_Trabajo/Estatus_de_Orden_de_Trabajo.module').then(m => m.Estatus_de_Orden_de_TrabajoModule) },
    { path: 'Estatus_Reporte', loadChildren: () => import('./views/Estatus_Reporte/Estatus_Reporte.module').then(m => m.Estatus_ReporteModule) },
    { path: 'Estatus_de_Proveedor', loadChildren: () => import('./views/Estatus_de_Proveedor/Estatus_de_Proveedor.module').then(m => m.Estatus_de_ProveedorModule) },
    { path: 'Estatus_de_remocion', loadChildren: () => import('./views/Estatus_de_remocion/Estatus_de_remocion.module').then(m => m.Estatus_de_remocionModule) },
    { path: 'Estatus_de_Reporte', loadChildren: () => import('./views/Estatus_de_Reporte/Estatus_de_Reporte.module').then(m => m.Estatus_de_ReporteModule) },
    { path: 'Estatus_de_Requerido', loadChildren: () => import('./views/Estatus_de_Requerido/Estatus_de_Requerido.module').then(m => m.Estatus_de_RequeridoModule) },
    { path: 'Estatus_de_Revision_en_Cotizacion', loadChildren: () => import('./views/Estatus_de_Revision_en_Cotizacion/Estatus_de_Revision_en_Cotizacion.module').then(m => m.Estatus_de_Revision_en_CotizacionModule) },
    { path: 'Estatus_de_Seguimiento', loadChildren: () => import('./views/Estatus_de_Seguimiento/Estatus_de_Seguimiento.module').then(m => m.Estatus_de_SeguimientoModule) },
    { path: 'Estatus_de_Seguimiento_de_Materiales', loadChildren: () => import('./views/Estatus_de_Seguimiento_de_Materiales/Estatus_de_Seguimiento_de_Materiales.module').then(m => m.Estatus_de_Seguimiento_de_MaterialesModule) },
    { path: 'Estatus_de_Solicitud_de_Compras', loadChildren: () => import('./views/Estatus_de_Solicitud_de_Compras/Estatus_de_Solicitud_de_Compras.module').then(m => m.Estatus_de_Solicitud_de_ComprasModule) },
    { path: 'Estatus_de_Solicitud_de_Compras_Generales', loadChildren: () => import('./views/Estatus_de_Solicitud_de_Compras_Generales/Estatus_de_Solicitud_de_Compras_Generales.module').then(m => m.Estatus_de_Solicitud_de_Compras_GeneralesModule) },
    { path: 'Estatus_de_Solicitud_de_Vuelo', loadChildren: () => import('./views/Estatus_de_Solicitud_de_Vuelo/Estatus_de_Solicitud_de_Vuelo.module').then(m => m.Estatus_de_Solicitud_de_VueloModule) },
    { path: 'Estatus_de_Usuario', loadChildren: () => import('./views/Estatus_de_Usuario/Estatus_de_Usuario.module').then(m => m.Estatus_de_UsuarioModule) },
    { path: 'Estatus_Detalle_Servicios_Asociados_Control_Componentes', loadChildren: () => import('./views/Estatus_Detalle_Servicios_Asociados_Control_Componentes/Estatus_Detalle_Servicios_Asociados_Control_Componentes.module').then(m => m.Estatus_Detalle_Servicios_Asociados_Control_ComponentesModule) },
    { path: 'Estatus_Gestion_Aprobacion', loadChildren: () => import('./views/Estatus_Gestion_Aprobacion/Estatus_Gestion_Aprobacion.module').then(m => m.Estatus_Gestion_AprobacionModule) },
    { path: 'Estatus_Modulo_de_Mantenimiento', loadChildren: () => import('./views/Estatus_Modulo_de_Mantenimiento/Estatus_Modulo_de_Mantenimiento.module').then(m => m.Estatus_Modulo_de_MantenimientoModule) },
    { path: 'Estatus_Notificacion', loadChildren: () => import('./views/Estatus_Notificacion/Estatus_Notificacion.module').then(m => m.Estatus_NotificacionModule) },
    { path: 'Estatus_Parte_Asociada_al_Componente', loadChildren: () => import('./views/Estatus_Parte_Asociada_al_Componente/Estatus_Parte_Asociada_al_Componente.module').then(m => m.Estatus_Parte_Asociada_al_ComponenteModule) },
    { path: 'Estatus_Tripulacion', loadChildren: () => import('./views/Estatus_Tripulacion/Estatus_Tripulacion.module').then(m => m.Estatus_TripulacionModule) },
    { path: 'Existencia_solicitud_crear_reporte', loadChildren: () => import('./views/Existencia_solicitud_crear_reporte/Existencia_solicitud_crear_reporte.module').then(m => m.Existencia_solicitud_crear_reporteModule) },
    { path: 'Fabricante', loadChildren: () => import('./views/Fabricante/Fabricante.module').then(m => m.FabricanteModule) },
    { path: 'Facturacion_de_Vuelo', loadChildren: () => import('./views/Facturacion_de_Vuelo/Facturacion_de_Vuelo.module').then(m => m.Facturacion_de_VueloModule) },
    { path: 'Filtros_de_reportes', loadChildren: () => import('./views/Filtros_de_reportes/Filtros_de_reportes.module').then(m => m.Filtros_de_reportesModule) },
    { path: 'Folios_Generacion_OC', loadChildren: () => import('./views/Folios_Generacion_OC/Folios_Generacion_OC.module').then(m => m.Folios_Generacion_OCModule) },
    { path: 'Forma_de_Pago', loadChildren: () => import('./views/Forma_de_Pago/Forma_de_Pago.module').then(m => m.Forma_de_PagoModule) },
    { path: 'Funcionalidades_para_Notificacion', loadChildren: () => import('./views/Funcionalidades_para_Notificacion/Funcionalidades_para_Notificacion.module').then(m => m.Funcionalidades_para_NotificacionModule) },
    { path: 'Gastos_de_Vuelo', loadChildren: () => import('./views/Gastos_de_Vuelo/Gastos_de_Vuelo.module').then(m => m.Gastos_de_VueloModule) },
    { path: 'Generacion_de_Orden_de_Compras', loadChildren: () => import('./views/Generacion_de_Orden_de_Compras/Generacion_de_Orden_de_Compras.module').then(m => m.Generacion_de_Orden_de_ComprasModule) },
    { path: 'Genero', loadChildren: () => import('./views/Genero/Genero.module').then(m => m.GeneroModule) },
    { path: 'Gestion_de_aprobacion', loadChildren: () => import('./views/Gestion_de_aprobacion/Gestion_de_aprobacion.module').then(m => m.Gestion_de_aprobacionModule) },
    { path: 'Historial_de_Cambios', loadChildren: () => import('./views/Historial_de_Cambios/Historial_de_Cambios.module').then(m => m.Historial_de_CambiosModule) },
    { path: 'Historial_de_Instalacion_de_partes', loadChildren: () => import('./views/Historial_de_Instalacion_de_partes/Historial_de_Instalacion_de_partes.module').then(m => m.Historial_de_Instalacion_de_partesModule) },
    { path: 'Historial_de_Remocion_de_partes', loadChildren: () => import('./views/Historial_de_Remocion_de_partes/Historial_de_Remocion_de_partes.module').then(m => m.Historial_de_Remocion_de_partesModule) },
    { path: 'Horarios_de_Trabajo', loadChildren: () => import('./views/Horarios_de_Trabajo/Horarios_de_Trabajo.module').then(m => m.Horarios_de_TrabajoModule) },
    { path: 'Husos_de_horarios', loadChildren: () => import('./views/Husos_de_horarios/Husos_de_horarios.module').then(m => m.Husos_de_horariosModule) },
    { path: 'Impresion_de_Bitacora_de_Vuelo', loadChildren: () => import('./views/Impresion_de_Bitacora_de_Vuelo/Impresion_de_Bitacora_de_Vuelo.module').then(m => m.Impresion_de_Bitacora_de_VueloModule) },
    { path: 'Gestion_de_Exportacion', loadChildren: () => import('./views/Gestion_de_Exportacion/Gestion_de_Exportacion.module').then(m => m.Gestion_de_ExportacionModule) },
    { path: 'Gestion_de_Importacion', loadChildren: () => import('./views/Gestion_de_Importacion/Gestion_de_Importacion.module').then(m => m.Gestion_de_ImportacionModule) },
    { path: 'Ingreso_a_almacen', loadChildren: () => import('./views/Ingreso_a_almacen/Ingreso_a_almacen.module').then(m => m.Ingreso_a_almacenModule) },
    { path: 'Ingreso_de_Componente', loadChildren: () => import('./views/Ingreso_de_Componente/Ingreso_de_Componente.module').then(m => m.Ingreso_de_ComponenteModule) },
    { path: 'Ingreso_de_Costos_de_Servicios', loadChildren: () => import('./views/Ingreso_de_Costos_de_Servicios/Ingreso_de_Costos_de_Servicios.module').then(m => m.Ingreso_de_Costos_de_ServiciosModule) },
    { path: 'Formato_de_salida_de_aeronave', loadChildren: () => import('./views/Formato_de_salida_de_aeronave/Formato_de_salida_de_aeronave.module').then(m => m.Formato_de_salida_de_aeronaveModule) },
    { path: 'Inspeccion_Entrada_Aeronave', loadChildren: () => import('./views/Inspeccion_Entrada_Aeronave/Inspeccion_Entrada_Aeronave.module').then(m => m.Inspeccion_Entrada_AeronaveModule) },
    { path: 'Instalacion', loadChildren: () => import('./views/Instalacion/Instalacion.module').then(m => m.InstalacionModule) },
    { path: 'Items', loadChildren: () => import('./views/Items/Items.module').then(m => m.ItemsModule) },
    { path: 'Layout_Balance_General', loadChildren: () => import('./views/Layout_Balance_General/Layout_Balance_General.module').then(m => m.Layout_Balance_GeneralModule) },
    { path: 'Layout_Cuentas_por_pagar', loadChildren: () => import('./views/Layout_Cuentas_por_pagar/Layout_Cuentas_por_pagar.module').then(m => m.Layout_Cuentas_por_pagarModule) },
    { path: 'Layout_Estado_de_Resultado', loadChildren: () => import('./views/Layout_Estado_de_Resultado/Layout_Estado_de_Resultado.module').then(m => m.Layout_Estado_de_ResultadoModule) },
    { path: 'Layout_Gastos', loadChildren: () => import('./views/Layout_Gastos/Layout_Gastos.module').then(m => m.Layout_GastosModule) },
    { path: 'Layout_Incidencia_Vuelos', loadChildren: () => import('./views/Layout_Incidencia_Vuelos/Layout_Incidencia_Vuelos.module').then(m => m.Layout_Incidencia_VuelosModule) },
    { path: 'Layout_Presupuestos', loadChildren: () => import('./views/Layout_Presupuestos/Layout_Presupuestos.module').then(m => m.Layout_PresupuestosModule) },
    { path: 'Layout_Presupuestos_Ventas', loadChildren: () => import('./views/Layout_Presupuestos_Ventas/Layout_Presupuestos_Ventas.module').then(m => m.Layout_Presupuestos_VentasModule) },
    { path: 'Layout_Proveedores', loadChildren: () => import('./views/Layout_Proveedores/Layout_Proveedores.module').then(m => m.Layout_ProveedoresModule) },
    { path: 'Lista_Predeterminada', loadChildren: () => import('./views/Lista_Predeterminada/Lista_Predeterminada.module').then(m => m.Lista_PredeterminadaModule) },
    { path: 'Listado_de_compras_en_proceso', loadChildren: () => import('./views/Listado_de_compras_en_proceso/Listado_de_compras_en_proceso.module').then(m => m.Listado_de_compras_en_procesoModule) },
    { path: 'Listado_de_compras_en_proceso_de_Exportacion', loadChildren: () => import('./views/Listado_de_compras_en_proceso_de_Exportacion/Listado_de_compras_en_proceso_de_Exportacion.module').then(m => m.Listado_de_compras_en_proceso_de_ExportacionModule) },
    { path: 'Listado_de_compras_en_proceso_de_Importacion', loadChildren: () => import('./views/Listado_de_compras_en_proceso_de_Importacion/Listado_de_compras_en_proceso_de_Importacion.module').then(m => m.Listado_de_compras_en_proceso_de_ImportacionModule) },
    { path: 'Listado_de_Directivas_de_aeronavegabilidad', loadChildren: () => import('./views/Listado_de_Directivas_de_aeronavegabilidad/Listado_de_Directivas_de_aeronavegabilidad.module').then(m => m.Listado_de_Directivas_de_aeronavegabilidadModule) },
    { path: 'Listado_de_Ordenes_de_Trabajo', loadChildren: () => import('./views/Listado_de_Ordenes_de_Trabajo/Listado_de_Ordenes_de_Trabajo.module').then(m => m.Listado_de_Ordenes_de_TrabajoModule) },
    { path: 'Listado_de_Pago_de_Proveedores', loadChildren: () => import('./views/Listado_de_Pago_de_Proveedores/Listado_de_Pago_de_Proveedores.module').then(m => m.Listado_de_Pago_de_ProveedoresModule) },
    { path: 'Listado_de_Vuelo_a_Facturar', loadChildren: () => import('./views/Listado_de_Vuelo_a_Facturar/Listado_de_Vuelo_a_Facturar.module').then(m => m.Listado_de_Vuelo_a_FacturarModule) },
    { path: 'Listado_Inspeccion_Inical', loadChildren: () => import('./views/Listado_Inspeccion_Inical/Listado_Inspeccion_Inical.module').then(m => m.Listado_Inspeccion_InicalModule) },
    { path: 'Medio_de_Comunicacion', loadChildren: () => import('./views/Medio_de_Comunicacion/Medio_de_Comunicacion.module').then(m => m.Medio_de_ComunicacionModule) },
    { path: 'Mes', loadChildren: () => import('./views/Mes/Mes.module').then(m => m.MesModule) },
    { path: 'Modulo_de_Mantenimiento', loadChildren: () => import('./views/Modulo_de_Mantenimiento/Modulo_de_Mantenimiento.module').then(m => m.Modulo_de_MantenimientoModule) },
    { path: 'Modulos_reportes', loadChildren: () => import('./views/Modulos_reportes/Modulos_reportes.module').then(m => m.Modulos_reportesModule) },
    { path: 'Moneda', loadChildren: () => import('./views/Moneda/Moneda.module').then(m => m.MonedaModule) },
    { path: 'Motivo_de_Edicion_de_Cotizacion', loadChildren: () => import('./views/Motivo_de_Edicion_de_Cotizacion/Motivo_de_Edicion_de_Cotizacion.module').then(m => m.Motivo_de_Edicion_de_CotizacionModule) },
    { path: 'Motivo_de_Viaje', loadChildren: () => import('./views/Motivo_de_Viaje/Motivo_de_Viaje.module').then(m => m.Motivo_de_ViajeModule) },
    { path: 'Motores', loadChildren: () => import('./views/Motores/Motores.module').then(m => m.MotoresModule) },
    { path: 'Nacionalidad', loadChildren: () => import('./views/Nacionalidad/Nacionalidad.module').then(m => m.NacionalidadModule) },
    { path: 'Nivel_de_Ruido', loadChildren: () => import('./views/Nivel_de_Ruido/Nivel_de_Ruido.module').then(m => m.Nivel_de_RuidoModule) },
    { path: 'Nombre_del_Campo_en_MS', loadChildren: () => import('./views/Nombre_del_Campo_en_MS/Nombre_del_Campo_en_MS.module').then(m => m.Nombre_del_Campo_en_MSModule) },
    { path: 'Notificacion_de_rechazo_al_ingreso_de_almacen', loadChildren: () => import('./views/Notificacion_de_rechazo_al_ingreso_de_almacen/Notificacion_de_rechazo_al_ingreso_de_almacen.module').then(m => m.Notificacion_de_rechazo_al_ingreso_de_almacenModule) },
    { path: 'Notificaciones_de_mantenimiento', loadChildren: () => import('./views/Notificaciones_de_mantenimiento/Notificaciones_de_mantenimiento.module').then(m => m.Notificaciones_de_mantenimientoModule) },
    { path: 'Notificaciones_Push', loadChildren: () => import('./views/Notificaciones_Push/Notificaciones_Push.module').then(m => m.Notificaciones_PushModule) },
    { path: 'Orden_de_servicio', loadChildren: () => import('./views/Orden_de_servicio/Orden_de_servicio.module').then(m => m.Orden_de_servicioModule) },
    { path: 'Orden_de_Trabajo', loadChildren: () => import('./views/Orden_de_Trabajo/Orden_de_Trabajo.module').then(m => m.Orden_de_TrabajoModule) },
    { path: 'Origen_de_Aeronave', loadChildren: () => import('./views/Origen_de_Aeronave/Origen_de_Aeronave.module').then(m => m.Origen_de_AeronaveModule) },
    { path: 'Pago_a_proveedores', loadChildren: () => import('./views/Pago_a_proveedores/Pago_a_proveedores.module').then(m => m.Pago_a_proveedoresModule) },
    { path: 'Pago_de_servicios_de_operaciones', loadChildren: () => import('./views/Pago_de_servicios_de_operaciones/Pago_de_servicios_de_operaciones.module').then(m => m.Pago_de_servicios_de_operacionesModule) },
    { path: 'Piezas', loadChildren: () => import('./views/Piezas/Piezas.module').then(m => m.PiezasModule) },
    { path: 'Piezas_Requeridas', loadChildren: () => import('./views/Piezas_Requeridas/Piezas_Requeridas.module').then(m => m.Piezas_RequeridasModule) },
    { path: 'Pistas', loadChildren: () => import('./views/Pistas/Pistas.module').then(m => m.PistasModule) },
    { path: 'Politica_de_Proveedores', loadChildren: () => import('./views/Politica_de_Proveedores/Politica_de_Proveedores.module').then(m => m.Politica_de_ProveedoresModule) },
    { path: 'Politicas_de_Precios_y_Descuentos', loadChildren: () => import('./views/Politicas_de_Precios_y_Descuentos/Politicas_de_Precios_y_Descuentos.module').then(m => m.Politicas_de_Precios_y_DescuentosModule) },
    { path: 'Pre_Solicitud_de_Cotizacion', loadChildren: () => import('./views/Pre_Solicitud_de_Cotizacion/Pre_Solicitud_de_Cotizacion.module').then(m => m.Pre_Solicitud_de_CotizacionModule) },
    { path: 'Presupuesto_Anual', loadChildren: () => import('./views/Presupuesto_Anual/Presupuesto_Anual.module').then(m => m.Presupuesto_AnualModule) },
    { path: 'Prioridad_del_Reporte', loadChildren: () => import('./views/Prioridad_del_Reporte/Prioridad_del_Reporte.module').then(m => m.Prioridad_del_ReporteModule) },
    { path: 'Procedencia', loadChildren: () => import('./views/Procedencia/Procedencia.module').then(m => m.ProcedenciaModule) },
    { path: 'Productividad_del_area_de_mantenimiento', loadChildren: () => import('./views/Productividad_del_area_de_mantenimiento/Productividad_del_area_de_mantenimiento.module').then(m => m.Productividad_del_area_de_mantenimientoModule) },
    { path: 'Propietarios', loadChildren: () => import('./views/Propietarios/Propietarios.module').then(m => m.PropietariosModule) },
    { path: 'proveedor_multi', loadChildren: () => import('./views/proveedor_multi/proveedor_multi.module').then(m => m.proveedor_multiModule) },
    { path: 'Proveedores_de_Seguros', loadChildren: () => import('./views/Proveedores_de_Seguros/Proveedores_de_Seguros.module').then(m => m.Proveedores_de_SegurosModule) },
    { path: 'Proveedores_para_MS', loadChildren: () => import('./views/Proveedores_para_MS/Proveedores_para_MS.module').then(m => m.Proveedores_para_MSModule) },
    { path: 'Razon_de_la_Compra', loadChildren: () => import('./views/Razon_de_la_Compra/Razon_de_la_Compra.module').then(m => m.Razon_de_la_CompraModule) },
    { path: 'Razon_de_Rechazo_a_Almacen', loadChildren: () => import('./views/Razon_de_Rechazo_a_Almacen/Razon_de_Rechazo_a_Almacen.module').then(m => m.Razon_de_Rechazo_a_AlmacenModule) },
    { path: 'Reabrir_vuelo', loadChildren: () => import('./views/Reabrir_vuelo/Reabrir_vuelo.module').then(m => m.Reabrir_vueloModule) },
    { path: 'Registro_de_Distancia_SENEAM', loadChildren: () => import('./views/Registro_de_Distancia_SENEAM/Registro_de_Distancia_SENEAM.module').then(m => m.Registro_de_Distancia_SENEAMModule) },
    { path: 'Ingreso_de_Costos', loadChildren: () => import('./views/Ingreso_de_Costos/Ingreso_de_Costos.module').then(m => m.Ingreso_de_CostosModule) },
    { path: 'Registro_de_vuelo', loadChildren: () => import('./views/Registro_de_vuelo/Registro_de_vuelo.module').then(m => m.Registro_de_vueloModule) },
    { path: 'Remocion_e_instalacion_de_piezas', loadChildren: () => import('./views/Remocion_e_instalacion_de_piezas/Remocion_e_instalacion_de_piezas.module').then(m => m.Remocion_e_instalacion_de_piezasModule) },
    { path: 'Reportes_para_OS', loadChildren: () => import('./views/Reportes_para_OS/Reportes_para_OS.module').then(m => m.Reportes_para_OSModule) },
    { path: 'Responsable_Incidencia_Vuelo', loadChildren: () => import('./views/Responsable_Incidencia_Vuelo/Responsable_Incidencia_Vuelo.module').then(m => m.Responsable_Incidencia_VueloModule) },
    { path: 'Respuesta', loadChildren: () => import('./views/Respuesta/Respuesta.module').then(m => m.RespuestaModule) },
    { path: 'Respuesta_del_Cliente_a_Cotizacion', loadChildren: () => import('./views/Respuesta_del_Cliente_a_Cotizacion/Respuesta_del_Cliente_a_Cotizacion.module').then(m => m.Respuesta_del_Cliente_a_CotizacionModule) },
    { path: 'Resultado_aprobacion_crear_reporte', loadChildren: () => import('./views/Resultado_aprobacion_crear_reporte/Resultado_aprobacion_crear_reporte.module').then(m => m.Resultado_aprobacion_crear_reporteModule) },
    { path: 'Resultado_de_Autorizacion_de_Vuelo', loadChildren: () => import('./views/Resultado_de_Autorizacion_de_Vuelo/Resultado_de_Autorizacion_de_Vuelo.module').then(m => m.Resultado_de_Autorizacion_de_VueloModule) },
    { path: 'Salida_en_almacen', loadChildren: () => import('./views/Salida_en_almacen/Salida_en_almacen.module').then(m => m.Salida_en_almacenModule) },
    { path: 'Seguimiento_de_Solicitud_de_Compras', loadChildren: () => import('./views/Seguimiento_de_Solicitud_de_Compras/Seguimiento_de_Solicitud_de_Compras.module').then(m => m.Seguimiento_de_Solicitud_de_ComprasModule) },
    { path: 'Seguros_Asociados_a_la_Aeronave', loadChildren: () => import('./views/Seguros_Asociados_a_la_Aeronave/Seguros_Asociados_a_la_Aeronave.module').then(m => m.Seguros_Asociados_a_la_AeronaveModule) },
    { path: 'Servicios', loadChildren: () => import('./views/Servicios/Servicios.module').then(m => m.ServiciosModule) },
    { path: 'Servicios_Herramientas_Adicionales_A_Solicitar', loadChildren: () => import('./views/Servicios_Herramientas_Adicionales_A_Solicitar/Servicios_Herramientas_Adicionales_A_Solicitar.module').then(m => m.Servicios_Herramientas_Adicionales_A_SolicitarModule) },
    { path: 'Servicios_Aduanales', loadChildren: () => import('./views/Servicios_Aduanales/Servicios_Aduanales.module').then(m => m.Servicios_AduanalesModule) },
    { path: 'Sexo', loadChildren: () => import('./views/Sexo/Sexo.module').then(m => m.SexoModule) },
    { path: 'Solicitud_de_Compras_Generales', loadChildren: () => import('./views/Solicitud_de_Compras_Generales/Solicitud_de_Compras_Generales.module').then(m => m.Solicitud_de_Compras_GeneralesModule) },
    { path: 'Solicitud_de_cotizacion', loadChildren: () => import('./views/Solicitud_de_cotizacion/Solicitud_de_cotizacion.module').then(m => m.Solicitud_de_cotizacionModule) },
    { path: 'Solicitud_de_Pagos_de_Servicios_de_Operaciones', loadChildren: () => import('./views/Solicitud_de_Pagos_de_Servicios_de_Operaciones/Solicitud_de_Pagos_de_Servicios_de_Operaciones.module').then(m => m.Solicitud_de_Pagos_de_Servicios_de_OperacionesModule) },
    { path: 'Solicitud_de_partes_materiales_y_herramientas', loadChildren: () => import('./views/Solicitud_de_partes_materiales_y_herramientas/Solicitud_de_partes_materiales_y_herramientas.module').then(m => m.Solicitud_de_partes_materiales_y_herramientasModule) },
    { path: 'Gestion_de_aprobacion_de_mantenimiento', loadChildren: () => import('./views/Gestion_de_aprobacion_de_mantenimiento/Gestion_de_aprobacion_de_mantenimiento.module').then(m => m.Gestion_de_aprobacion_de_mantenimientoModule) },
    { path: 'Solicitud_de_Servicios_para_Operaciones', loadChildren: () => import('./views/Solicitud_de_Servicios_para_Operaciones/Solicitud_de_Servicios_para_Operaciones.module').then(m => m.Solicitud_de_Servicios_para_OperacionesModule) },
    { path: 'Solicitud_de_Vuelo', loadChildren: () => import('./views/Solicitud_de_Vuelo/Solicitud_de_Vuelo.module').then(m => m.Solicitud_de_VueloModule) },
    { path: 'Solicitudes_de_mantenimientos_externos', loadChildren: () => import('./views/Solicitudes_de_mantenimientos_externos/Solicitudes_de_mantenimientos_externos.module').then(m => m.Solicitudes_de_mantenimientos_externosModule) },
    { path: 'Tarifas_de_Vuelo_de_Aeronave', loadChildren: () => import('./views/Tarifas_de_Vuelo_de_Aeronave/Tarifas_de_Vuelo_de_Aeronave.module').then(m => m.Tarifas_de_Vuelo_de_AeronaveModule) },
    { path: 'Tiempo_de_remocion', loadChildren: () => import('./views/Tiempo_de_remocion/Tiempo_de_remocion.module').then(m => m.Tiempo_de_remocionModule) },
    { path: 'Tipo_Concepto', loadChildren: () => import('./views/Tipo_Concepto/Tipo_Concepto.module').then(m => m.Tipo_ConceptoModule) },
    { path: 'Tipo_Concepto_Estado_Resultado', loadChildren: () => import('./views/Tipo_Concepto_Estado_Resultado/Tipo_Concepto_Estado_Resultado.module').then(m => m.Tipo_Concepto_Estado_ResultadoModule) },
    { path: 'Tipo_de_Accion_Notificacion', loadChildren: () => import('./views/Tipo_de_Accion_Notificacion/Tipo_de_Accion_Notificacion.module').then(m => m.Tipo_de_Accion_NotificacionModule) },
    { path: 'Tipo_de_Aeropuerto', loadChildren: () => import('./views/Tipo_de_Aeropuerto/Tipo_de_Aeropuerto.module').then(m => m.Tipo_de_AeropuertoModule) },
    { path: 'Tipo_de_Ala', loadChildren: () => import('./views/Tipo_de_Ala/Tipo_de_Ala.module').then(m => m.Tipo_de_AlaModule) },
    { path: 'Tipo_de_Aviso', loadChildren: () => import('./views/Tipo_de_Aviso/Tipo_de_Aviso.module').then(m => m.Tipo_de_AvisoModule) },
    { path: 'Tipo_de_Bitacora_de_Aeronave', loadChildren: () => import('./views/Tipo_de_Bitacora_de_Aeronave/Tipo_de_Bitacora_de_Aeronave.module').then(m => m.Tipo_de_Bitacora_de_AeronaveModule) },
    { path: 'Tipo_de_Boletin', loadChildren: () => import('./views/Tipo_de_Boletin/Tipo_de_Boletin.module').then(m => m.Tipo_de_BoletinModule) },
    { path: 'Tipo_de_carga', loadChildren: () => import('./views/Tipo_de_carga/Tipo_de_carga.module').then(m => m.Tipo_de_cargaModule) },
    { path: 'Tipo_de_Cliente', loadChildren: () => import('./views/Tipo_de_Cliente/Tipo_de_Cliente.module').then(m => m.Tipo_de_ClienteModule) },
    { path: 'Tipo_de_Concepto_Balance_General', loadChildren: () => import('./views/Tipo_de_Concepto_Balance_General/Tipo_de_Concepto_Balance_General.module').then(m => m.Tipo_de_Concepto_Balance_GeneralModule) },
    { path: 'Tipo_de_Condicion_Aeronave', loadChildren: () => import('./views/Tipo_de_Condicion_Aeronave/Tipo_de_Condicion_Aeronave.module').then(m => m.Tipo_de_Condicion_AeronaveModule) },
    { path: 'Tipo_de_Condicion_Parte', loadChildren: () => import('./views/Tipo_de_Condicion_Parte/Tipo_de_Condicion_Parte.module').then(m => m.Tipo_de_Condicion_ParteModule) },
    { path: 'Tipo_de_Destino', loadChildren: () => import('./views/Tipo_de_Destino/Tipo_de_Destino.module').then(m => m.Tipo_de_DestinoModule) },
    { path: 'Tipo_de_Documentacion_Aeronave', loadChildren: () => import('./views/Tipo_de_Documentacion_Aeronave/Tipo_de_Documentacion_Aeronave.module').then(m => m.Tipo_de_Documentacion_AeronaveModule) },
    { path: 'Tipo_de_Documentacion_PAXs', loadChildren: () => import('./views/Tipo_de_Documentacion_PAXs/Tipo_de_Documentacion_PAXs.module').then(m => m.Tipo_de_Documentacion_PAXsModule) },
    { path: 'Tipo_de_Equipo_de_Emergencia', loadChildren: () => import('./views/Tipo_de_Equipo_de_Emergencia/Tipo_de_Equipo_de_Emergencia.module').then(m => m.Tipo_de_Equipo_de_EmergenciaModule) },
    { path: 'Tipo_de_Equipo_de_Supervivencia', loadChildren: () => import('./views/Tipo_de_Equipo_de_Supervivencia/Tipo_de_Equipo_de_Supervivencia.module').then(m => m.Tipo_de_Equipo_de_SupervivenciaModule) },
    { path: 'Tipo_de_Gasto', loadChildren: () => import('./views/Tipo_de_Gasto/Tipo_de_Gasto.module').then(m => m.Tipo_de_GastoModule) },
    { path: 'Tipo_de_Grupo', loadChildren: () => import('./views/Tipo_de_Grupo/Tipo_de_Grupo.module').then(m => m.Tipo_de_GrupoModule) },
    { path: 'Tipo_de_Hospedaje', loadChildren: () => import('./views/Tipo_de_Hospedaje/Tipo_de_Hospedaje.module').then(m => m.Tipo_de_HospedajeModule) },
    { path: 'Tipo_de_Ingreso_a_Cotizacion', loadChildren: () => import('./views/Tipo_de_Ingreso_a_Cotizacion/Tipo_de_Ingreso_a_Cotizacion.module').then(m => m.Tipo_de_Ingreso_a_CotizacionModule) },
    { path: 'Tipo_de_Ingreso_de_Gasto', loadChildren: () => import('./views/Tipo_de_Ingreso_de_Gasto/Tipo_de_Ingreso_de_Gasto.module').then(m => m.Tipo_de_Ingreso_de_GastoModule) },
    { path: 'Tipo_de_Instalacion', loadChildren: () => import('./views/Tipo_de_Instalacion/Tipo_de_Instalacion.module').then(m => m.Tipo_de_InstalacionModule) },
    { path: 'Tipo_de_Medio_de_Comunicacion', loadChildren: () => import('./views/Tipo_de_Medio_de_Comunicacion/Tipo_de_Medio_de_Comunicacion.module').then(m => m.Tipo_de_Medio_de_ComunicacionModule) },
    { path: 'Tipo_de_Miscelaneas', loadChildren: () => import('./views/Tipo_de_Miscelaneas/Tipo_de_Miscelaneas.module').then(m => m.Tipo_de_MiscelaneasModule) },
    { path: 'Tipo_de_Notificacion', loadChildren: () => import('./views/Tipo_de_Notificacion/Tipo_de_Notificacion.module').then(m => m.Tipo_de_NotificacionModule) },
    { path: 'Tipo_de_Notificacion_Push', loadChildren: () => import('./views/Tipo_de_Notificacion_Push/Tipo_de_Notificacion_Push.module').then(m => m.Tipo_de_Notificacion_PushModule) },
    { path: 'Tipo_de_origen_del_reporte', loadChildren: () => import('./views/Tipo_de_origen_del_reporte/Tipo_de_origen_del_reporte.module').then(m => m.Tipo_de_origen_del_reporteModule) },
    { path: 'Tipo_de_Piloto', loadChildren: () => import('./views/Tipo_de_Piloto/Tipo_de_Piloto.module').then(m => m.Tipo_de_PilotoModule) },
    { path: 'Tipo_de_Posicion_de_Piezas', loadChildren: () => import('./views/Tipo_de_Posicion_de_Piezas/Tipo_de_Posicion_de_Piezas.module').then(m => m.Tipo_de_Posicion_de_PiezasModule) },
    { path: 'Tipo_de_producto', loadChildren: () => import('./views/Tipo_de_producto/Tipo_de_producto.module').then(m => m.Tipo_de_productoModule) },
    { path: 'Tipo_de_Recordatorio_Notificacion', loadChildren: () => import('./views/Tipo_de_Recordatorio_Notificacion/Tipo_de_Recordatorio_Notificacion.module').then(m => m.Tipo_de_Recordatorio_NotificacionModule) },
    { path: 'Tipo_de_Reporte', loadChildren: () => import('./views/Tipo_de_Reporte/Tipo_de_Reporte.module').then(m => m.Tipo_de_ReporteModule) },
    { path: 'Tipo_de_Seguro', loadChildren: () => import('./views/Tipo_de_Seguro/Tipo_de_Seguro.module').then(m => m.Tipo_de_SeguroModule) },
    { path: 'Tipo_de_Servicios_Aduanales', loadChildren: () => import('./views/Tipo_de_Servicios_Aduanales/Tipo_de_Servicios_Aduanales.module').then(m => m.Tipo_de_Servicios_AduanalesModule) },
    { path: 'Tipo_de_Solicitud_de_Compras', loadChildren: () => import('./views/Tipo_de_Solicitud_de_Compras/Tipo_de_Solicitud_de_Compras.module').then(m => m.Tipo_de_Solicitud_de_ComprasModule) },
    { path: 'Tipo_de_Transportacion', loadChildren: () => import('./views/Tipo_de_Transportacion/Tipo_de_Transportacion.module').then(m => m.Tipo_de_TransportacionModule) },
    { path: 'Tipo_de_Transporte', loadChildren: () => import('./views/Tipo_de_Transporte/Tipo_de_Transporte.module').then(m => m.Tipo_de_TransporteModule) },
    { path: 'Tipo_de_Tripulante', loadChildren: () => import('./views/Tipo_de_Tripulante/Tipo_de_Tripulante.module').then(m => m.Tipo_de_TripulanteModule) },
    { path: 'Tipo_de_urgencia', loadChildren: () => import('./views/Tipo_de_urgencia/Tipo_de_urgencia.module').then(m => m.Tipo_de_urgenciaModule) },
    { path: 'Tipo_de_vuelo', loadChildren: () => import('./views/Tipo_de_vuelo/Tipo_de_vuelo.module').then(m => m.Tipo_de_vueloModule) },
    { path: 'Tipo_Dia_Notificacion', loadChildren: () => import('./views/Tipo_Dia_Notificacion/Tipo_Dia_Notificacion.module').then(m => m.Tipo_Dia_NotificacionModule) },
    { path: 'Tipo_Frecuencia_Notificacion', loadChildren: () => import('./views/Tipo_Frecuencia_Notificacion/Tipo_Frecuencia_Notificacion.module').then(m => m.Tipo_Frecuencia_NotificacionModule) },
    { path: 'Tipo_Incidencia_Vuelos', loadChildren: () => import('./views/Tipo_Incidencia_Vuelos/Tipo_Incidencia_Vuelos.module').then(m => m.Tipo_Incidencia_VuelosModule) },
    { path: 'Tipo_orden_de_servicio', loadChildren: () => import('./views/Tipo_orden_de_servicio/Tipo_orden_de_servicio.module').then(m => m.Tipo_orden_de_servicioModule) },
    { path: 'Tipo_Persona_Notificar', loadChildren: () => import('./views/Tipo_Persona_Notificar/Tipo_Persona_Notificar.module').then(m => m.Tipo_Persona_NotificarModule) },
    { path: 'Tipos_de_Curso', loadChildren: () => import('./views/Tipos_de_Curso/Tipos_de_Curso.module').then(m => m.Tipos_de_CursoModule) },
    { path: 'Tipos_de_Modelo_Curso', loadChildren: () => import('./views/Tipos_de_Modelo_Curso/Tipos_de_Modelo_Curso.module').then(m => m.Tipos_de_Modelo_CursoModule) },
    { path: 'Tipos_de_Origen_del_Componente', loadChildren: () => import('./views/Tipos_de_Origen_del_Componente/Tipos_de_Origen_del_Componente.module').then(m => m.Tipos_de_Origen_del_ComponenteModule) },
    { path: 'Tipos_de_proveedor', loadChildren: () => import('./views/Tipos_de_proveedor/Tipos_de_proveedor.module').then(m => m.Tipos_de_proveedorModule) },
    { path: 'Toma_de_Tiempos_a_aeronaves', loadChildren: () => import('./views/Toma_de_Tiempos_a_aeronaves/Toma_de_Tiempos_a_aeronaves.module').then(m => m.Toma_de_Tiempos_a_aeronavesModule) },
    { path: 'Tripulacion', loadChildren: () => import('./views/Tripulacion/Tripulacion.module').then(m => m.TripulacionModule) },
    { path: 'Turbulencia_de_Estela', loadChildren: () => import('./views/Turbulencia_de_Estela/Turbulencia_de_Estela.module').then(m => m.Turbulencia_de_EstelaModule) },
    { path: 'Unidad', loadChildren: () => import('./views/Unidad/Unidad.module').then(m => m.UnidadModule) },
    { path: 'Urgencia', loadChildren: () => import('./views/Urgencia/Urgencia.module').then(m => m.UrgenciaModule) },
    { path: 'Utilidad', loadChildren: () => import('./views/Utilidad/Utilidad.module').then(m => m.UtilidadModule) },
    { path: 'Tipo_de_Orden_de_Trabajo', loadChildren: () => import('./views/Tipo_de_Orden_de_Trabajo/Tipo_de_Orden_de_Trabajo.module').then(m => m.Tipo_de_Orden_de_TrabajoModule) },
    { path: 'Report', loadChildren: () => import('./views/Detalle_Reporte/detalle-reporte.module').then(m => m.DetalleReporteModule) },
    
    { path: 'Calendario', loadChildren: () => import('./views/Calendario/calendario.module').then(m => m.CalendarioModule) },
    { path: 'Detalle_de_Actividades_de_Colaboradores', loadChildren: () => import('./views/Detalle_de_Actividades_de_Colaboradores/Detalle_de_Actividades_de_Colaboradores.module').then(m => m.Detalle_de_Actividades_de_ColaboradoresModule) },

    /*@@INCLUDE@@*/
];
@NgModule({
    imports: [RouterModule.forRoot(routes, { useHash: true, onSameUrlNavigation: 'ignore' })],
    exports: [RouterModule]
})
export class AppRoutingModule { }
